cms-kr/TZWi

NanoAODProduction/python/customise_cff.py, NanoAODProduction/test/generateConfig.sh, README.md, TopAnalysis/python/ttbarDoubleLepton.py, TopAnalysis/test/prod_ntuple/run.sh
=> rename pakcage name

README.md, TopAnalysis/interface/CombineHLTCppWorker.h, TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h, TopAnalysis/python/ttbarDoubleLepton.py, TopAnalysis/python/ttbarDoubleLeptonHLT.py, TopAnalysis/src/CombineHLTCppWorker.cc, TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc, TopAnalysis/test/prod_ntuple/run.sh
=> HLT worder

TopAnalysis/python/ttbarDoubleLeptonHLT.py, TopAnalysis/test/prod_ntuple/run.sh
Bug, typo fix, flags were not filled in correctly.
=> Bugfix fill Flags

TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h, TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc
Just a placeholder to keep cutflow bits.
=> Cutflow branch - a placeholder

TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h, TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc
1. Add stepcut in the analysis code
2. Change type of nStepCut to integer.
=> Add stepcut

TopAnalysis/interface/PartonTopCppWorker.h, TopAnalysis/python/partonTop.py, TopAnalysis/src/PartonTopCppWorker.cc, TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc, TopAnalysis/test/prod_ntuple/run.sh
Technical changes for the code quality.
=> Coding convention etc

NanoAODProduction/python/customise_cff.py, NanoAODProduction/python/customise_dropNanoAODTables_cff.py, NanoAODProduction/python/customise_particletop_cff.py, NanoAODProduction/test/generateConfig.sh
NanoAOD only with the particle level top objects are produced.
These files will be joined with the usual standard NanoAOD, with friend-tree or hadd, whatever.
=> Particle level top-only NanoAOD

TopAnalysis/python/ttbarDoubleLeptonHLT.py, TopAnalysis/src/CombineHLTCppWorker.cc, TopAnalysis/test/prod_ntuple/run.sh
HLT module was not running due to a typo
HLT path name is updated for MC
some technical changes to introduce alternative function to set branch addresses
=> Bugfix running on MC + technical changes

NanoAODProduction/interface/TTbarModeDefs.h, NanoAODProduction/plugins/BuildFile.xml, NanoAODProduction/plugins/PartonTopProducer.cc, NanoAODProduction/python/customise_partontop_cff.py, NanoAODProduction/python/producers/partonTop_cfi.py, NanoAODProduction/test/generateConfig.sh
Add PartonTop in the TOP-MC customized NanoAOD
=> Add PartonTop 

NanoAODProduction/python/customise_particleTop_cff.py, NanoAODProduction/python/customise_partonTop_cff.py, NanoAODProduction/python/tables/partonTop_cff.py, NanoAODProduction/test/generateConfig.sh
further follow file naming convention.
=> Fine tune, file names

TopAnalysis/data/combineHLT/flags/MC_RunIISummer16.json, TopAnalysis/data/combineHLT/flags/RD_Run2016.json, TopAnalysis/data/combineHLT/ttbarDoubleLepton/MC_RunIISummer16.json, TopAnalysis/data/combineHLT/ttbarDoubleLepton/RD_Run2016BG.json, TopAnalysis/data/combineHLT/ttbarDoubleLepton/RD_Run2016H.json, TopAnalysis/interface/CombineHLTCppWorker.h, TopAnalysis/python/CombineHLT.py, TopAnalysis/python/ttbarDoubleLeptonHLT.py, TopAnalysis/src/CombineHLTCppWorker.cc
Upgrade CombineHLT postprocessor to use TFormula.
Formula will be given in TopAnalysis/data/combineHLT.
=> TFormula based HLT combiner

README.md, TopAnalysis/interface/PartonTopCppWorker.h, TopAnalysis/python/partonTop.py, TopAnalysis/src/PartonTopCppWorker.cc, TopAnalysis/test/prod_ntuple/run.sh
PartonTop postprocessor is modified to use NanoAODTools supported interface for brach booking and filling.
Additional bugfixes are done in the run script.
=> PartonTopPostProcessor uses framework supported branch

TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h, TopAnalysis/python/ttbarDoubleLepton.py, TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc
Update dilepton postprocess to use the NanoAODTools framework supported branch actions.
- Note: to be finished after merging @yhlee52 's PR #22 
- Next to come: split cut flow postprocessor from this event reconstruction postprocessor.
=> Dilepton postprocessor to use framework branch output

TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h, TopAnalysis/python/ttbarDoubleLepton.py, TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh, TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
Additional changes to use NanoAODTools framework supported output
Mostly to fix typos because of copy and paste.
=> Additional fixes to use framework supported output

TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h, TopAnalysis/python/ttbarDoubleLepton.py, TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc, TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh, TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
There were some roll-backed coded accidentally...
=> Redo code changes

TopAnalysis/data/combineHLT/flags/MC_RunIIFall17.json, TopAnalysis/data/combineHLT/flags/RD_Run2017.json, TopAnalysis/python/ttbarDoubleLeptonHLT.py
Fix typo on the flag and change unused flag filter.
Recover MC2017 HLT.
=> Fix typo on flag and HLT

TopAnalysis/interface/FCNCTriLeptonCppWorker.h, TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h, TopAnalysis/python/fcncTriLepton.py, TopAnalysis/src/FCNCTriLeptonCppWorker.cc, TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc
Series of PR to update tree booking for FCNC analyzer.
Relateed PR: #26
=> Framework supported tree booking and filling

TopAnalysis/interface/FCNCTriLeptonCppWorker.h, TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h, TopAnalysis/python/fcncTriLepton.py, TopAnalysis/python/fcncTriLeptonCutFlow.py, TopAnalysis/python/ttbarDoubleLepton.py, TopAnalysis/python/ttbarDoubleLeptonCutFlow.py, TopAnalysis/python/ttbarDoubleLeptonHLT.py, TopAnalysis/src/FCNCTriLeptonCppWorker.cc, TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc, TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh, TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
Implemented separate Cut flow postprocessor, which takes output of previous module.
Note: this is just a workaround. there could be a framework-supported method...
=> Cut Flow analyzer in a separate postprocessor

TopAnalysis/python/fcncTriLeptonCutFlow.py, TopAnalysis/src/FCNCTriLeptonCppWorker.cc, TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh
Finalize migration to a separate postproc module - for FCNC.
Some bugfix because of copy & paste without attension.
=> Separate postproc migration

TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh, TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
Protection from wrong channel input such as ElMuMu <-> MuMuEl
=> protection from flipped channel input

NanoAODProduction/data/datasets/MiniAOD/2016/MC.RunIISummer16.central.yaml, NanoAODProduction/data/datasets/NanoAOD/2016/RD.Run2016.yaml, NanoAODProduction/data/datasets/NanoAOD/2017/RD.Run2017.yaml
Small modification of yaml for the NanoAOD, can add path to the root files.
=> change yaml structure for NanoAOD

NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml, NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.rareprocess.yaml, NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.syst.yaml
nanoAOD MC sample lists are updated by .yaml configuration
Check it please
=> 2016 MC sample list update from tsv

NanoAODProduction/data/datasets/NanoAOD/2017/RD.Run2017.yaml, TopAnalysis/python/ttbarDoubleLeptonCutFlow.py
2017 data set list is added as yaml format. Wrong condition is changed on the ttbarcutflow.
=> Add 2017 Dataset list as yaml format

TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
B tag SF postprocessor is added. 
PUWeight is changed to use 2017.
=> Add btagSF postproc, fix puweight to use 2017

TopAnalysis/data/combineHLT/fcncTriLepton/2016.yaml, TopAnalysis/python/CombineHLT.py, TopAnalysis/python/fcncTriLeptonHLT.py, TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh
There was no NOT character (!) in CombineHLT.py. So I wrote it.
And we need to change run.sh in trilepton channel because HLT is little bit different by data periods.(There are 3 groups)
Until now, I don't know exactly how should I change 'run.sh' working on seperated groups
=> bugfix in 'CombineHLT.py' & change 'run.sh' in trilepton channel

TopAnalysis/src/FCNCTriLeptonCppWorker.cc
=> bugfix calling tight id

TopAnalysis/python/fcncTriLepton.py, TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh
We must use summer16 cutbased id. so it need to be change.
=> Changing the Electron cutbased id

TopAnalysis/interface/FCNCTriLeptonCppWorker.h, TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h, TopAnalysis/python/btagWeightProducer.py, TopAnalysis/python/fcncTriLepton.py, TopAnalysis/python/fcncTriLeptonCutFlow.py, TopAnalysis/python/ttbarDoubleLepton.py, TopAnalysis/python/ttbarDoubleLeptonCutFlow.py, TopAnalysis/src/FCNCTriLeptonCppWorker.cc, TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc, TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh, TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
- Add BtagWeight producer
- Results from previous postprocessor module is sent to the next one in better way - use "input" tree object, no more direct access to output branches
- Change function naming scheme - Jets -> Jet
=> BtagWeight producer, better inter-module object handling

TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
output directory (keep the same scheme of fcnc <-> ttbb)
=> output directory

TopAnalysis/python/CombineHLT.py, TopAnalysis/python/CopyBranch.py, TopAnalysis/python/btagWeightProducer.py, TopAnalysis/python/fcncTriLepton.py, TopAnalysis/python/fcncTriLeptonHLT.py, TopAnalysis/python/ttbarDoubleLeptonCutFlow.py, TopAnalysis/python/ttbarDoubleLeptonHLT.py, TopAnalysis/test/fcncTriLepton/prod_ntuple/run.sh, TopAnalysis/test/ttbarDoubleLepton/prod_ntuple/run.sh
Adding a postprocessor to copy existing branch(es).
First version works only for non-array variable, added PV_npvsGood.
=> Branch copying postprocessor

NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml, NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.rareprocess.yaml, NanoAODProduction/data/datasets/NanoAOD/2016/RD.Run2016.yaml, NanoAODProduction/data/datasets/NanoAOD/2017/RD.Run2017.yaml, NanoAODProduction/scripts/tzwi-udpatedataset
New script is added, lists up available root files for each dataset.
=> New script to list up available nanoAOD files

TopAnalysis/data/histogramming/ttbbDilepton.yaml, TopAnalysis/scripts/tzwi-makehistograms, TopAnalysis/test/ttbarDoubleLepton/02_make_histograms.sh
Histogram step works without crash.
Cut flow histogram is filled in.
=> Non-crashing histogramming step

TopAnalysis/data/combineHLT/ttbarDoubleLepton/2017.yaml
=> Fix error on 2017 MuonEG HLT

NanoAODProduction/data/datasets/NanoAOD/2017/MC.RunIIFall17.central.yaml, NanoAODProduction/scripts/tzwi-updatedataset, TopAnalysis/test/fcncTriLepton/01_prod_ntuple.sh, TopAnalysis/test/ttbarDoubleLepton/01_prod_ntuple.sh
Changing directory structure for the filelist
=> Change directory structure

TopAnalysis/src/FCNCTriLeptonCppWorker.cc
We care about the lepton which has the largest pt. And in our analysis, It should comes from W boson.
So I changed lepton1 -> W, lepton2,3 -> Z. And add some line that comparing the pt.
Please check about this.
=> Save lepton1,2,3 in order of pt

TopAnalysis/test/ttbarDoubleLepton/02_make_histograms.py
=> bugfix typo

NanoAODProduction/scripts/tzwi-updatedataset
Require grid proxy in tzwi-updatedataset.
#82
=> Require grid proxy

NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml, TopAnalysis/src/FCNCTriLeptonCppWorker.cc
For now, just adding goodleptoncode = -111, and open the PR
I will modified Z and W boson candidate soon.
=> Adding GoodLeptonCode = -111 & change the Z and W candidated lepton

NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.rareprocess.yaml, TopAnalysis/interface/FCNCTriLeptonCppWorker.h, TopAnalysis/src/FCNCTriLeptonCppWorker.cc
Rearrange leptons by the possible charge pairings.
We prefer to have leptons from Z to be opposite signed and same flavour among first 3 leptons in pT.
=> Rearrange leptons by their charge pairing

TopAnalysis/data/combineHLT/ttbarDoubleLepton/2016.yaml, TopAnalysis/interface/TTbarDoubleLeptonCppWorker.h, TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc
Add 2016 single lepton trigger and fix double lepton trigger.
=> 2016 single leptron trigger

NanoAODProduction/scripts/tzwi-updatedataset
Use XRootD python module to put SE URL, first try T3, continue to T2, otherwise set it to the global xrd.
@geonmo
=> use XRootD python module to select nearest SE

NanoAODProduction/scripts/tzwi-updatedataset
=> bugfix keep file handle in xrood client

NanoAODProduction/scripts/tzwi-associateDatasets
New script to map different NanoAOD ntuples by run/lumi
=> File mapping

NanoAODProduction/scripts/tzwi-updatedataset
updatedataset script looks at local directory
=> tune updatedataset 

NanoAODProduction/data/crosssection/13TeV.yaml, TopAnalysis/data/grouping/ttbbDilepton.yaml, TopAnalysis/data/histogramming/ttbbDilepton.yaml, TopAnalysis/data/plots/ttbbDilepton.yaml, TopAnalysis/scripts/tzwi-makehistograms, TopAnalysis/test/fcncTriLepton/02_make_histograms.py, TopAnalysis/test/ttbarDoubleLepton/02_make_histograms.py, TopAnalysis/test/ttbarDoubleLepton/03_scalemerge.py, TopAnalysis/test/ttbarDoubleLepton/04_drawPlots.py, TopAnalysis/test/ttbarDoubleLepton/config/crosssection.yaml, TopAnalysis/test/ttbarDoubleLepton/config/datasets/MC.RunIISummer16.central.yaml, TopAnalysis/test/ttbarDoubleLepton/config/datasets/MC.RunIISummer16.rareprocess.yaml, TopAnalysis/test/ttbarDoubleLepton/config/datasets/MC.RunIISummer16.syst.yaml, TopAnalysis/test/ttbarDoubleLepton/config/datasets/RD.Run2016.yaml, TopAnalysis/test/ttbarDoubleLepton/config/grouping.yaml, TopAnalysis/test/ttbarDoubleLepton/config/histogramming.yaml, TopAnalysis/test/ttbarDoubleLepton/config/plots.yaml, TopAnalysis/test/ttbarDoubleLepton/config/systematics.yaml
First version of the plotting tools
=> Plotting tool for ttbb dilepton

TopAnalysis/test/ttbarDoubleLepton/03_scalemerge.py, TopAnalysis/test/ttbarDoubleLepton/04_drawPlots.py
=> Plotting bugfix

NanoAODProduction/data/crosssection/13TeV.yaml, NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml, NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.syst.yaml, TopAnalysis/data/grouping/fcncTrilepton.yaml, TopAnalysis/test/common/01.2_checkFailed.sh, TopAnalysis/test/common/03_scalemerge.py, TopAnalysis/test/fcncTriLepton/01.1_submit.sh, TopAnalysis/test/fcncTriLepton/01.2_checkFailed.sh, TopAnalysis/test/ttbarDoubleLepton/01.1_submit.sh, TopAnalysis/test/ttbarDoubleLepton/01.2_checkFailed.sh
Additional scripts for job submission
Process "names" are changed
=> Job submission tools, process names

NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml, NanoAODProduction/scripts/tzwi-updatedataset, TopAnalysis/data/combineHLT/ttbarDoubleLepton/2016.yaml, TopAnalysis/data/grouping/fcncTrilepton.yaml, TopAnalysis/data/histogramming/fcncTrilepton.yaml, TopAnalysis/data/histogramming/ttbbDilepton.yaml, TopAnalysis/test/common/01.2_checkFailed.sh, TopAnalysis/test/fcncTriLepton/01.1_submit.sh, TopAnalysis/test/fcncTriLepton/02_make_histograms.py, TopAnalysis/test/ttbarDoubleLepton/01.1_submit.sh, TopAnalysis/test/ttbarDoubleLepton/02_make_histograms.py
Technical updates
- das client API rather than system calls
- add W+nJets samples
- change sample naming convention - TT_powheg -> TT.powheg
- technical fix for job submission scripts
=> Technical updates

NanoAODProduction/scripts/tzwi-updatedataset, TopAnalysis/scripts/tzwi-makehistograms, TopAnalysis/test/common/04_drawPlots.py
=> Technical changes

TopAnalysis/data/grouping/fcncTrilepton.yaml, TopAnalysis/data/grouping/ttbbDilepton.yaml
genWeight sign was not considered by accident.
=> Fix wrong genWeight - missing weight sign

TopAnalysis/test/fcncTriLepton/01.1_submit.py, TopAnalysis/test/ttbarDoubleLepton/01.1_submit.py
=> submit jobs under a subdirectory, bugfix

NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml, NanoAODProduction/data/datasets/NanoAOD/2016/RD.Run2016.yaml, TopAnalysis/data/combineHLT/ttbarDoubleLepton/2016.yaml, TopAnalysis/data/histogramming/ttbbDilepton.yaml, TopAnalysis/data/plots/ttbbDilepton.yaml, TopAnalysis/python/postprocessing/ttbarDoubleLeptonCutFlow.py, TopAnalysis/python/postprocessing/ttbarDoubleLeptonHLT.py, TopAnalysis/test/ttbarDoubleLepton/01_prod_ntuple.sh
1. Add single lepton trigger.(A bug is. Should be fixed)
2. Add missed cutstep condition for step1 (Z_mass>20GeV)
3. Add missed diboson dataset(WW, WZ, ZZ)
4. change plotting color and binning.
=> Single lepton trig, cutstep, diboson dataset, plotting

TopAnalysis/data/histogramming/ttbbDilepton.yaml, TopAnalysis/test/common/04_drawPlots.py
Plotting tool generates a html page.
=> Better plotting

TopAnalysis/data/grouping/ttbbDilepton.yaml, TopAnalysis/data/plots/ttbbDilepton.yaml, TopAnalysis/test/common/03_scalemerge.py, TopAnalysis/test/common/04_drawPlots.py
=> Plotting bugfix + better styling

TopAnalysis/scripts/tzwi-makehistograms, TopAnalysis/test/common/04_drawPlots.py
=> minor fixes for fcnc plotting

NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml, TopAnalysis/data/histogramming/fcncTrilepton.yaml, TopAnalysis/test/fcncTriLepton/01.1_submit.py, TopAnalysis/test/ttbarDoubleLepton/01.1_submit.py
=> plotting update

TopAnalysis/data/grouping/fcncTrilepton.yaml, TopAnalysis/data/grouping/ttbbDilepton.yaml, TopAnalysis/data/histogramming/fcncTrilepton.yaml, TopAnalysis/data/plots/fcncTrilepton.yaml, TopAnalysis/scripts/tzwi-makehistograms, TopAnalysis/test/common/02_make_histograms.py, TopAnalysis/test/common/03_scalemerge.py
Various fixes for plotting in multiple channels / datasets.
=> Fix to plotting

TopAnalysis/data/histogramming/fcncTrilepton.yaml, TopAnalysis/data/plots/fcncTrilepton.yaml
I already checked the transverse mass of W boson plot was well contained in histogram root file.
And chaingin the stackorder to Singletops are stacked first.
Please check it.
=> Adding & changing histogramming

TopAnalysis/data/combineHLT/ttbarDoubleLepton/2016.yaml, TopAnalysis/python/postprocessing/fcncTriLeptonHLT.py, TopAnalysis/python/postprocessing/ttbarDoubleLeptonHLT.py
Fix wrong input to the CombineHLT logic.
=> Fix HLT formula, closure for lambda expression

TopAnalysis/test/ttbarDoubleLepton/01_prod_ntuple.sh
=> HLT module name fix for ttbb

TopAnalysis/data/combineHLT/ttbarDoubleLepton/2016.yaml, TopAnalysis/data/grouping/fcncTrilepton.yaml, TopAnalysis/data/grouping/ttbbDilepton.yaml, TopAnalysis/data/plots/ttbbDilepton.yaml, TopAnalysis/python/postprocessing/fcncTriLeptonHLT.py, TopAnalysis/python/postprocessing/ttbarDoubleLeptonHLT.py, TopAnalysis/test/common/04_drawPlots.py, TopAnalysis/test/fcncTriLepton/01.1_submit.py, TopAnalysis/test/ttbarDoubleLepton/01.1_submit.py
=> Cleanup codes

TopAnalysis/test/common/02_make_histograms.py, TopAnalysis/test/common/03_scalemerge.py, TopAnalysis/test/common/04_drawPlots.py
=> Improve plotting

TopAnalysis/data/grouping/fcncTrilepton.yaml, TopAnalysis/data/histogramming/fcncTrilepton.yaml, TopAnalysis/test/common/03_scalemerge.py, TopAnalysis/test/common/04_drawPlots.py
=> FCNC signal regions, sample selection

TopAnalysis/test/ttbarDoubleLepton/TTBB.py, TopAnalysis/test/ttbarDoubleLepton/ttbb.txt
Datacard and fitting formula maker for higgs combine tool.
=> Datacard and fit formula for combine tool

NanoAODProduction/python/customise_cff.py, NanoAODProduction/python/customise_genTop_cff.py, NanoAODProduction/python/tables/genTop_cff.py
For gentop production.(Not finished)
=> gentop production

NanoAODProduction/data/branchsel_JEC.txt, NanoAODProduction/test/nano4jes/NanoAOD, NanoAODProduction/test/nano4jes/run.sh, NanoAODProduction/test/nano4jes/submit.py
NANOAOD to JES-only  NANOAOD production scripts @yhlee52
=> JES-only NANOAOD production

NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml, TopAnalysis/python/postprocessing/fcncTriLeptonCutFlow.py, TopAnalysis/src/FCNCTriLeptonCppWorker.cc
Some of the asymptotic datasets had a typo, so the file location did not fill in .yaml file.
And I added lepton rearranged when leptons are saved in the same flavour mode.
Please check these!
=> update datasets and lepton rearranged

NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml, NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.rareprocess.yaml
=> NanoAODv5 MC list update

NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.rareprocess.yaml
Erase zeta lines of FCNC signal MCs.
=> Fix error on MC rare list

NanoAODProduction/data/crosssection/13TeV.yaml, NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml, NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.rareprocess.yaml, TopAnalysis/data/combineHLT/fcncTriLepton/2016.yaml, TopAnalysis/data/combineHLT/fcncTriLepton/2016_bkup.yaml, TopAnalysis/data/grouping/fcncTrilepton.yaml, TopAnalysis/data/grouping/fcncTrilepton_2017.yaml, TopAnalysis/data/histogramming/fcncTrilepton.yaml, TopAnalysis/data/plots/fcncTrilepton.yaml, TopAnalysis/interface/FCNCTriLeptonCppWorker.h, TopAnalysis/python/postprocessing/fcncTriLepton.py, TopAnalysis/python/postprocessing/fcncTriLeptonHLT.py, TopAnalysis/src/FCNCTriLeptonCppWorker.cc, TopAnalysis/test/common/01.2_checkFailed.sh, TopAnalysis/test/fcncTriLepton/01.1_submit.py
Changed selections are coming from Taiwan group selections.
Please comment If these codes have any wrong things.
=> Changing selections for 2016 datasets

TopAnalysis/interface/FCNCTriLeptonCppWorker.h, TopAnalysis/src/FCNCTriLeptonCppWorker.cc
Refactor FCNC module code
@jeongsumin please consider submitting jobs AFTER finalizing this PR.
=> Refactor FCNC module

TopAnalysis/interface/FCNCTriLeptonCppWorker.h, TopAnalysis/python/postprocessing/fcncTriLepton.py, TopAnalysis/src/FCNCTriLeptonCppWorker.cc, TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc
Implement NPL selection
Simplify routines, event selection logic
=> implement NPL selection, simplify selection

TopAnalysis/python/postprocessing/fcncTriLepton.py
vid map naming pattern is different for 2016 and 2017+
=> change default vid map name

TopAnalysis/data/grouping/fcncTrilepton.yaml, TopAnalysis/data/histogramming/fcncTrilepton.yaml, TopAnalysis/data/plots/fcncTrilepton.yaml, TopAnalysis/python/postprocessing/fcncTriLepton.py, TopAnalysis/test/fcncTriLepton/01.1_submit.py
Electron_vid need to change because it has the wrong object name
And .yaml files need to be updated because NPL part was added.
=> fixed error & update plotting .yaml for NPL

NanoAODProduction/data/crosssection/13TeV.yaml, NanoAODProduction/data/datasets/NanoAOD/2016/MC.RunIISummer16.central.yaml, TopAnalysis/data/grouping/fcncTrilepton.yaml, TopAnalysis/data/histogramming/fcncTrilepton.yaml, TopAnalysis/data/plots/fcncTrilepton.yaml, TopAnalysis/interface/FCNCTriLeptonCppWorker.h, TopAnalysis/python/postprocessing/fcncTriLepton.py, TopAnalysis/python/postprocessing/fcncTriLeptonCutFlow.py, TopAnalysis/src/FCNCTriLeptonCppWorker.cc
This PR should be contained about modified NPL logic.
But for now, the title of this PR only said omission because I just add 3mu mode in worker file.
So the title will be changed after trying to change the NPL logic.
=> Adding the omission thing & modifying the NPL logic

TopAnalysis/src/TTbarDoubleLeptonCppWorker.cc, TopAnalysis/test/common/01.2_checkFailed.sh, TopAnalysis/test/ttbarDoubleLepton/01.1_submit.py, TopAnalysis/test/ttbarDoubleLepton/01_prod_ntuple.sh
=> ttbar dilepton bugfix

NanoAODProduction/data/branchsel.txt, TopAnalysis/data/grouping/fcncTrilepton.yaml, TopAnalysis/data/histogramming/fcncTrilepton.yaml, TopAnalysis/python/postprocessing/fcncKinematicReco.py, TopAnalysis/test/fcncTriLepton/01_prod_ntuple.sh, TopAnalysis/test/fcncTriLepton/bkgestFit_working.py
Top kinematic reconstruction : fcncKinematicReco.py
Bkg estimation : bkgest_working.py
1. Top kin reco
- Reconstruction algorithm is validated.
- Top kin reco postprocessor only save two top events. : Now this command is commented out.
2. Bkg estimation
- This code is working but fit result does not look good.
- Now the code makes few png files for visualize fit result and one txt file with estimated result.
- Change plot cosmetics and get entries from fitting function.
- Suggested output : Save the result as .yaml format and use it for new control plots.
3. Missed LeptonSF
- LeptonSF is added on the plot drawing step.
=> Top reconstruction and data-driven background estimation from WZCR/TTCR.

README.md, TopAnalysis/data/histogramming/fcncTrilepton.yaml, TopAnalysis/test/fcncTriLepton/01_prod_ntuple.sh
Updating both files because of the deepjet b discriminator for 2016 samples.
Modifying STCR & adding STCR_allZ step that equal to TTCR(_allZ).
=> Updating README and shell script

TopAnalysis/python/postprocessing/fcncKinematicReco.py, TopAnalysis/python/postprocessing/fcncMVAinput.py, TopAnalysis/test/fcncTriLepton/01_prod_ntuple.sh, TopAnalysis/test/fcncTriLepton/bkgestFit_working.py
3 updates on framework
1. Gaussian constraint on fit parameters of background estimation
- Take gaussian constraint on fit parameters with mean=initial ration, sigma=mean/2
- Will be these constraint condition changed or not?
2. Top reconstruction with NPL channels
- Top reconstruction is worked on NPL channels with NPLflag.(tested)
3.  MVAinput postprocessor
- Just make "MVAinput_*" branches on central ntuple.
- Real MVA input root file generator will be updated.
=> Gaussian const on bkg est, top reco with NPL, MVAinput generator

NanoAODProduction/data/branchsel.txt, NanoAODProduction/data/crosssection/13TeV.yaml, TopAnalysis/python/postprocessing/fcncMVAinput.py, TopAnalysis/test/fcncTriLepton/bkgestFit_working.py
3 changes on this PR.
1. Draw NLL curve(contour) for fit parameters.
2. TTCR estimation method is changed.
3. xsecNorm is added on MVAinput to give weight on TMVA.(Hard-coded yet)
=> Draw NLL for fit, TTCR change, xsecNorm on MVAinput
